PUT http://localhost:3001/api/persons/66c1291ec7d8570c7fd110b9
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "643-234-876"
}

###

GET http://localhost:3001/api/persons/66c1291ec7d8570c7fd110b2


###

DELETE http://localhost:3001/api/persons/1