PUT http://localhost:3001/api/persons/66bf886fd9d038838b047c39
Content-Type: application/json

{
    "name": "Arto hellas",
    "number": "643-234-876"
}

###

GET http://localhost:3001/api/persons/66bf885c70ba4f17c24fc9e7


###

DELETE http://localhost:3001/api/persons/1